### ISSUE TITLE
Question about serial bridge

### ISSUE THREAD

**Issue by Silverquark** [nepeee/i3Extra#1]
First of all the serial bridge is an awesome idea.
But i cant quite get my head around how it works.
Do you just have to send all files through the serial port if lcd is in update mode?
If so then whats the best way to do it using windows?
Are you using the SSCOM3.2 Software linked on the DWIN page [here](http://dwin.com.cn/english/products/bt-72876584214435.html)

**Comment by nepeee** [comment]
No i think the SSCOM3.2 is a simple terminal program. I used the dgus serial assistant, it comes with the sdk. In bridge mode the marlin sw simply redirects all messages between the main serial port(usb) and the lcd serial port. I increased the serial baud rates from 115200 to 250000(maximum common baud rate for the lcd and atmega with acceptable error rate) but the transfer is extremely slow about 30sec/bitmap.

**Comment by Silverquark** [comment]
Okay thanks. Helped me very much. Too bad its so slow. Still usefull for debugging though!

**Comment by OmgItsBkid** [comment]
I still wasn't able to get this working properly. Is the serial connection supposed to be opening on the same baud rate as the original connection? I noticed MYSERIAL in the original code and Serial2 are both opening on 115200.

Even after pressing the LCD update button on the screen, I still can't seem to establish a connection to send the LCD firmware. What could I be doing wrong, and what exact software were you using for the connection/transfer?

**Comment by nepeee** [comment]
You must set the R3 byte to 5A and the RA to A5(frame start bytes) in the DGUS Serial Assistant. I pushed the current version of the project files to the repo with the baud rate change. Before using the new version you must update the lcd fw with the sd card method first!
